library(methods)
m1 <- Matrix::sparse.model.matrix(~ ., iris)
m2 <- as(m1, "RsparseMatrix")
stopifnot(class(m1) == "dgCMatrix")
m2 <- as(m1, "dgTMatrix")
stopifnot(class(m2) == "dgTMatrix")
m3 <- as(m2, "RsparseMatrix")
stopifnot(class(m3) == "dgRMatrix")
m.all <- list(m1, m2, m3)

set.seed(1)
x1.1 <- rnorm(ncol(m1))
x1.2 <- rnorm(nrow(m1))
