// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/Xv.h"
#include <Rcpp.h>

using namespace Rcpp;

// Xv_dgCMatrix_numeric
SEXP Xv_dgCMatrix_numeric(S4 x, NumericVector y);
RcppExport SEXP Xv_Xv_dgCMatrix_numeric(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(Xv_dgCMatrix_numeric(x, y));
    return rcpp_result_gen;
END_RCPP
}
// _Xv_dgCMatrix_numeric
SEXP _Xv_dgCMatrix_numeric(S4 X, NumericVector v, IntegerVector foldid, int target, bool is_exclude);
RcppExport SEXP Xv__Xv_dgCMatrix_numeric(SEXP XSEXP, SEXP vSEXP, SEXP foldidSEXP, SEXP targetSEXP, SEXP is_excludeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type foldid(foldidSEXP);
    Rcpp::traits::input_parameter< int >::type target(targetSEXP);
    Rcpp::traits::input_parameter< bool >::type is_exclude(is_excludeSEXP);
    rcpp_result_gen = Rcpp::wrap(_Xv_dgCMatrix_numeric(X, v, foldid, target, is_exclude));
    return rcpp_result_gen;
END_RCPP
}
// Xv_dgTMatrix_numeric
SEXP Xv_dgTMatrix_numeric(S4 x, NumericVector y);
RcppExport SEXP Xv_Xv_dgTMatrix_numeric(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(Xv_dgTMatrix_numeric(x, y));
    return rcpp_result_gen;
END_RCPP
}
// _Xv_dgTMatrix_numeric
SEXP _Xv_dgTMatrix_numeric(S4 X, NumericVector v, IntegerVector foldid, int target, bool is_exclude);
RcppExport SEXP Xv__Xv_dgTMatrix_numeric(SEXP XSEXP, SEXP vSEXP, SEXP foldidSEXP, SEXP targetSEXP, SEXP is_excludeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type foldid(foldidSEXP);
    Rcpp::traits::input_parameter< int >::type target(targetSEXP);
    Rcpp::traits::input_parameter< bool >::type is_exclude(is_excludeSEXP);
    rcpp_result_gen = Rcpp::wrap(_Xv_dgTMatrix_numeric(X, v, foldid, target, is_exclude));
    return rcpp_result_gen;
END_RCPP
}
// Xv_dgRMatrix_numeric
SEXP Xv_dgRMatrix_numeric(S4 x, NumericVector y);
RcppExport SEXP Xv_Xv_dgRMatrix_numeric(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(Xv_dgRMatrix_numeric(x, y));
    return rcpp_result_gen;
END_RCPP
}
// _Xv_dgRMatrix_numeric
SEXP _Xv_dgRMatrix_numeric(S4 X, NumericVector v, IntegerVector foldid, int target, bool is_exclude);
RcppExport SEXP Xv__Xv_dgRMatrix_numeric(SEXP XSEXP, SEXP vSEXP, SEXP foldidSEXP, SEXP targetSEXP, SEXP is_excludeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type foldid(foldidSEXP);
    Rcpp::traits::input_parameter< int >::type target(targetSEXP);
    Rcpp::traits::input_parameter< bool >::type is_exclude(is_excludeSEXP);
    rcpp_result_gen = Rcpp::wrap(_Xv_dgRMatrix_numeric(X, v, foldid, target, is_exclude));
    return rcpp_result_gen;
END_RCPP
}
// vX_numeric_dgCMatrix
SEXP vX_numeric_dgCMatrix(NumericVector x, S4 y);
RcppExport SEXP Xv_vX_numeric_dgCMatrix(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< S4 >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(vX_numeric_dgCMatrix(x, y));
    return rcpp_result_gen;
END_RCPP
}
// _vX_dgCMatrix_numeric
SEXP _vX_dgCMatrix_numeric(S4 X, NumericVector v, IntegerVector foldid, int target, bool is_exclude);
RcppExport SEXP Xv__vX_dgCMatrix_numeric(SEXP XSEXP, SEXP vSEXP, SEXP foldidSEXP, SEXP targetSEXP, SEXP is_excludeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type foldid(foldidSEXP);
    Rcpp::traits::input_parameter< int >::type target(targetSEXP);
    Rcpp::traits::input_parameter< bool >::type is_exclude(is_excludeSEXP);
    rcpp_result_gen = Rcpp::wrap(_vX_dgCMatrix_numeric(X, v, foldid, target, is_exclude));
    return rcpp_result_gen;
END_RCPP
}
// vX_numeric_dgTMatrix
SEXP vX_numeric_dgTMatrix(NumericVector x, S4 y);
RcppExport SEXP Xv_vX_numeric_dgTMatrix(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< S4 >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(vX_numeric_dgTMatrix(x, y));
    return rcpp_result_gen;
END_RCPP
}
// _vX_dgTMatrix_numeric
SEXP _vX_dgTMatrix_numeric(S4 X, NumericVector v, IntegerVector foldid, int target, bool is_exclude);
RcppExport SEXP Xv__vX_dgTMatrix_numeric(SEXP XSEXP, SEXP vSEXP, SEXP foldidSEXP, SEXP targetSEXP, SEXP is_excludeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type foldid(foldidSEXP);
    Rcpp::traits::input_parameter< int >::type target(targetSEXP);
    Rcpp::traits::input_parameter< bool >::type is_exclude(is_excludeSEXP);
    rcpp_result_gen = Rcpp::wrap(_vX_dgTMatrix_numeric(X, v, foldid, target, is_exclude));
    return rcpp_result_gen;
END_RCPP
}
// vX_numeric_dgRMatrix
SEXP vX_numeric_dgRMatrix(NumericVector x, S4 y);
RcppExport SEXP Xv_vX_numeric_dgRMatrix(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< S4 >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(vX_numeric_dgRMatrix(x, y));
    return rcpp_result_gen;
END_RCPP
}
// _vX_dgRMatrix_numeric
SEXP _vX_dgRMatrix_numeric(S4 X, NumericVector v, IntegerVector foldid, int target, bool is_exclude);
RcppExport SEXP Xv__vX_dgRMatrix_numeric(SEXP XSEXP, SEXP vSEXP, SEXP foldidSEXP, SEXP targetSEXP, SEXP is_excludeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type foldid(foldidSEXP);
    Rcpp::traits::input_parameter< int >::type target(targetSEXP);
    Rcpp::traits::input_parameter< bool >::type is_exclude(is_excludeSEXP);
    rcpp_result_gen = Rcpp::wrap(_vX_dgRMatrix_numeric(X, v, foldid, target, is_exclude));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"Xv_Xv_dgCMatrix_numeric", (DL_FUNC) &Xv_Xv_dgCMatrix_numeric, 2},
    {"Xv__Xv_dgCMatrix_numeric", (DL_FUNC) &Xv__Xv_dgCMatrix_numeric, 5},
    {"Xv_Xv_dgTMatrix_numeric", (DL_FUNC) &Xv_Xv_dgTMatrix_numeric, 2},
    {"Xv__Xv_dgTMatrix_numeric", (DL_FUNC) &Xv__Xv_dgTMatrix_numeric, 5},
    {"Xv_Xv_dgRMatrix_numeric", (DL_FUNC) &Xv_Xv_dgRMatrix_numeric, 2},
    {"Xv__Xv_dgRMatrix_numeric", (DL_FUNC) &Xv__Xv_dgRMatrix_numeric, 5},
    {"Xv_vX_numeric_dgCMatrix", (DL_FUNC) &Xv_vX_numeric_dgCMatrix, 2},
    {"Xv__vX_dgCMatrix_numeric", (DL_FUNC) &Xv__vX_dgCMatrix_numeric, 5},
    {"Xv_vX_numeric_dgTMatrix", (DL_FUNC) &Xv_vX_numeric_dgTMatrix, 2},
    {"Xv__vX_dgTMatrix_numeric", (DL_FUNC) &Xv__vX_dgTMatrix_numeric, 5},
    {"Xv_vX_numeric_dgRMatrix", (DL_FUNC) &Xv_vX_numeric_dgRMatrix, 2},
    {"Xv__vX_dgRMatrix_numeric", (DL_FUNC) &Xv__vX_dgRMatrix_numeric, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_Xv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
