# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Xv_dgCMatrix_numeric <- function(x, y) {
    .Call(Xv_Xv_dgCMatrix_numeric, x, y)
}

Xv_dgCMatrix_numeric_folded <- function(x, v, foldid, target, is_exclude) {
    .Call(Xv_Xv_dgCMatrix_numeric_folded, x, v, foldid, target, is_exclude)
}

Xv_dgTMatrix_numeric <- function(x, y) {
    .Call(Xv_Xv_dgTMatrix_numeric, x, y)
}

Xv_dgRMatrix_numeric <- function(x, y) {
    .Call(Xv_Xv_dgRMatrix_numeric, x, y)
}

vX_numeric_dgCMatrix <- function(x, y) {
    .Call(Xv_vX_numeric_dgCMatrix, x, y)
}

vX_numeric_dgTMatrix <- function(x, y) {
    .Call(Xv_vX_numeric_dgTMatrix, x, y)
}

vX_numeric_dgRMatrix <- function(x, y) {
    .Call(Xv_vX_numeric_dgRMatrix, x, y)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('Xv_RcppExport_registerCCallable', PACKAGE = 'Xv')
})
